[package]
name = "uiop-dsp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
log = "0.4.26"
nom = "8.0.0"
simple_logger = "5.0.0"
strum = "0.27.1"
strum_macros = "0.27.1"
tokio = { version = "1.44.1", features = ["full"] }
